cursor #e2e2e2
cursor_text_color #c6c6c6

foreground            #e2e2e2
background            #131313
selection_foreground  #352d40
selection_background  #cec2da
url_color             #d7baff

color0   #131313
color1   #ff728d
color2   #7fff9c
color3   #ffda72
color4   #c4a3f2
color5   #543b76
color6   #d7baff
color7   #f6efff
color8   #9e99a5
color9   #ff9fb1
color10  #a5ffb9
color11  #ffe8a5
color12  #ddc4ff
color13  #e3ceff
color14  #ecdfff
color15  #fbf8ff
